name: Run EFFIS Burned Area Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Ejecuta todos los días a las 06:00 UTC

jobs:
  run-effis:
    runs-on: ubuntu-latest
    container:
      image: rocker/geospatial:4.3.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install additional R packages
        run: |
          Rscript -e 'install.packages(c("dplyr"), repos = "https://cloud.r-project.org")'

      - name: Run script (nrt.ba)
        run: Rscript R/effis_ba_tiles.R --layer=nrt.ba

      - name: Run script (modis.ba)
        run: Rscript R/effis_ba_tiles.R --layer=modis.ba

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bo]()
